image: python:3.7

stages:
    - quality
    - build
    - dist

cache:
    paths:
        - bin/
        - eggs/
        - parts/

before_script:
    - apt update && apt install -y iputils-ping
    - ping -c 1 -W 1 172.17.0.1 && export http_proxy=http://172.17.0.1:3128/
    - ping -c 1 -W 1 172.17.0.1 && export HTTP_PROXY=http://172.17.0.1:3128/
    - ping -c 1 -W 1 172.17.0.1 && export https_proxy=http://172.17.0.1:3128/
    - ping -c 1 -W 1 172.17.0.1 && export HTTPS_PROXY=http://172.17.0.1:3128/

bootstrap:
    stage: .pre
    script:
        - pip install pip==22.3.1 setuptools==65.6.3 zc.buildout==3.0.1 zc.recipe.egg==2.0.7
        - buildout

pylint:
    stage: quality
    allow_failure: true
    script:
        - pip install pylint-exit anybadge zc.buildout==3.0.1
        - buildout
        - mkdir ./pylint
        - ./bin/pylint src/pyams_chat_ws/ | tee ./pylint/pylint.log || pylint-exit $?
        - PYLINT_SCORE=$(sed -n 's/^Your code has been rated at \([-0-9.]*\)\/.*/\1/p' ./pylint/pylint.log)
        - anybadge --label=Pylint --file=./pylint/pylint.svg --value=$PYLINT_SCORE pylint
        - echo "Pylint score is $PYLINT_SCORE"
    artifacts:
        paths:
            - ./pylint/

build-3.7:
    stage: build
    script:
        - pip install zc.buildout==3.0.1
        - buildout setup setup.py clean --all sdist
    artifacts:
        paths:
            - ./dist
    only:
        refs:
            - tags

dist-3.7:
    stage: dist
    script:
        - pip install pip==22.3.1 setuptools==65.6.3 zc.buildout==3.0.1 zc.recipe.egg==2.0.7
        - buildout
        - buildout setup setup.py sdist bdist_wheel
        - pip install twine
        - twine upload --skip-existing dist/*
    variables:
        TWINE_USERNAME: $PYPI_USERNAME
        TWINE_PASSWORD: $PYPI_PASSWORD
    only:
        refs:
            - tags
    except:
        variables:
            - $PYPI_UPLOAD_DISABLED

dist-3.8:
    stage: dist
    image: python:3.8
    script:
        - pip install pip==22.3.1 setuptools==65.6.3 zc.buildout==3.0.1 zc.recipe.egg==2.0.7
        - buildout
        - buildout setup setup.py bdist_wheel
        - pip install twine
        - twine upload --skip-existing dist/*
    variables:
        TWINE_USERNAME: $PYPI_USERNAME
        TWINE_PASSWORD: $PYPI_PASSWORD
    only:
        refs:
            - tags
    except:
        variables:
            - $PYPI_UPLOAD_DISABLED

dist-3.9:
    stage: dist
    image: python:3.9
    script:
        - pip install pip==22.3.1 setuptools==65.6.3 zc.buildout==3.0.1 zc.recipe.egg==2.0.7
        - buildout
        - buildout setup setup.py bdist_wheel
        - pip install twine
        - twine upload --skip-existing dist/*
    variables:
        TWINE_USERNAME: $PYPI_USERNAME
        TWINE_PASSWORD: $PYPI_PASSWORD
    only:
        refs:
            - tags
    except:
        variables:
            - $PYPI_UPLOAD_DISABLED

dist-3.10:
    stage: dist
    image: python:3.10
    script:
        - pip install pip==22.3.1 setuptools==65.6.3 zc.buildout==3.0.1 zc.recipe.egg==2.0.7
        - buildout
        - buildout setup setup.py bdist_wheel
        - pip install twine
        - twine upload --skip-existing dist/*
    variables:
        TWINE_USERNAME: $PYPI_USERNAME
        TWINE_PASSWORD: $PYPI_PASSWORD
    only:
        refs:
            - tags
    except:
        variables:
            - $PYPI_UPLOAD_DISABLED

dist-3.11:
    stage: dist
    image: python:3.11
    script:
        - pip install pip==22.3.1 setuptools==65.6.3 zc.buildout==3.0.1 zc.recipe.egg==2.0.7
        - buildout
        - buildout setup setup.py bdist_wheel
        - pip install twine
        - twine upload --skip-existing dist/*
    variables:
        TWINE_USERNAME: $PYPI_USERNAME
        TWINE_PASSWORD: $PYPI_PASSWORD
    only:
        refs:
            - tags
    except:
        variables:
            - $PYPI_UPLOAD_DISABLED
